### ISSUE TITLE
OpenSSL Apple review issue

### ISSUE THREAD

**Issue by OJDee** [Judopay/DeviceDNA-iOS#15]
We are receiving this issue with submission to Apple Review. App is using JudoKit-iOS, which In turns uses DeviceDNA, which in turns uses OpenSSL.

ITMS-91065: Missing signature - Your app includes “Frameworks/OpenSSL.framework/OpenSSL”, which includes BoringSSL / openssl_grpc, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. If a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a signature file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a signature. For details about verifying the code signature for a third-party SDK, visit: https://developer.apple.com/documentation/xcode/verifying-the-origin-of-your-xcframeworks.

Removing JudoKit-iOS from project also removes OpenSSL dependency, and issue is resolved with Apple.

Appears that latest JudoKit-iOS version 3.4.0 -> DeviceDNA version 2.1.0 -> OpenSSL version 1.1.2200 (aug 2023)

We are using SPM for integration. Please can you advise on this?

**Comment by stefan-tudor** [comment]
Hey @OJDee,
thank you for reporting this!

Release https://github.com/Judopay/DeviceDNA-iOS/releases/tag/2.1.1 drops
OpenSSL-Universal and MIHCrypto libraries in favour of iOS default CommonCrypto and Security frameworks,
also adds code signing and privacy manifests, which should fix this issue.

**Comment by OJDee** [comment]
@stefan-tudor Having re-added Judokit-iOS 3.4.2 using SPM, we can see that Device-DNA 2.1.1 is also injected, however we are still having app refused for the same OpenSSL reason as above.

**Comment by stefan-tudor** [comment]
@OJDee Device-DNA 2.1.1 has no traces of OpenSSL anymore https://github.com/Judopay/DeviceDNA-iOS/blob/master/Package.swift,
Maybe OpenSSL is a transient dependency on other libraries you're using.

Run this to find out `swift package show-dependencies --format json`
